### ISSUE TITLE
Test case suite fails on Neo4j v 2.3

### ISSUE THREAD

**Issue by corporatepiyush** [codex-digital/cypher-stream#20]
I am getting an error with Neo4J 2.3 and Node 4.2.2

> cypher-stream@0.3.0 test /Users/redpanda/work/github/cypher-stream
> make test

./node_modules/.bin/mocha -b
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.

  ․․

  1 passing (656ms)
  1 failing

  1) Cypher stream handles errors:

      expected 'AssertionError
      + expected - actual

      +"Error: Query Failure: Invalid input 'i': expected <init> (line 1, column 1)\n\"invalid query\"\n ^"
      -"AssertionError: expected 'Error: Query Failure: Invalid input \\'i\\': expected <init> (line 1, column 1 (offset: 0))\\n\"invalid query\"\\n ^' to be 'Error: Query Failure: Invalid input \\'i\\': expected <init> (line 1, column 1)\\n\"invalid query\"\\n ^'"
      
      at Assertion.prop.(anonymous function) [as exactly] (/Users/redpanda/work/github/cypher-stream/node_modules/should/lib/should.js:60:14)
      at CypherStream.<anonymous> (/Users/redpanda/work/github/cypher-stream/test/cypher-stream-test.js:50:30)
      at emitOne (events.js:77:13)
      at CypherStream.emit (events.js:169:7)
      at CypherStreamHandleFailure (/Users/redpanda/work/github/cypher-stream/CypherStream.js:182:12)
      at applyEach (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:496:20)
      at Object.emit (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1929:10)
      at /Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:2323:33
      at apply (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:171:14)
      at /Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:2300:10
      at applyEach (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:496:20)
      at emit (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1929:10)
      at emitMatchingNode (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:2104:7)
      at /Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:2149:13
      at applyEach (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:496:20)
      at emit (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1929:10)
      at nodeClosed (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1494:7)
      at /Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1048:19
      at applyEach (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:496:20)
      at emit (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1929:10)
      at handleData (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:761:14)
      at applyEach (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:496:20)
      at Object.emit (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1929:10)
      at IncomingMessage.<anonymous> (/Users/redpanda/work/github/cypher-stream/node_modules/oboe/dist/oboe-node.js:1128:34)
      at emitOne (events.js:77:13)
      at IncomingMessage.emit (events.js:169:7)
      at IncomingMessage.Readable.read (_stream_readable.js:360:10)
      at flow (_stream_readable.js:743:26)
      at resume_ (_stream_readable.js:723:3)
      at doNTCallback2 (node.js:441:9)
      at process._tickCallback (node.js:355:17)

make: *** [test] Error 1
npm ERR! Test failed.  See above for more details.

**Comment by brian-gates** [comment]
This issue fell between the cracks, I apologize.  We've been using this on 2.3 for a while.  We're now on 3.0 though, so I don't think this is applicable anymore.  If you still need help, let me know, but I assume this issue is no longer valid, so closing.  Feel free to reopen if it's still relevant.
